apiVersion: apps/v1
kind: Deployment
metadata:
  name: goserver-deployment
  labels:
    app: goserver
spec:
  selector:
    matchLabels:
      app: goserver
  replicas: 1
  template:
    metadata:
      labels:
        app: goserver
    spec:
      containers:
        - name: goserver
          image: sharran/goserverdemo
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
          env:
            - name: ENV_VAR
              valueFrom:
                configMapKeyRef:
                  name: goserver-config-map
                  key: hello_env
---
#External Service configuration
apiVersion: v1
kind: Service
metadata:
  name: goserver-service
spec:
  selector:
    app: goserver
  type: LoadBalancer #If you add this tag, then the service becomes external service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30000
